#set page(numbering: "1")
#import "@preview/ctheorems:1.1.3": *
#show: thmrules
#let lemma = thmbox("lemma", "Lemma", base: none)
#let problem = thmbox("problem", "Problem", base: none)
#let theorem = thmbox("theorem", "Theorem", base: none)
#let proof = thmproof("proof", "Proof")
#set math.mat(delim: "[")
#set math.equation(numbering: "(1)")

#show math.equation: it => {
  if it.block and not it.has("label") and it.numbering != none {
    counter(math.equation).update(v => v - 1)
    
    // Fix: Create a dictionary of fields, remove 'body', 
    // and pass 'it.body' positionally.
    let fields = it.fields()
    let _ = fields.remove("body") 
    
    math.equation(it.body, ..fields, numbering: none)
  } else {
    it
  }
}

#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  it
}

#outline(depth: 1)

= Artin 2.3.1
#problem[
  Prove that the additive group $RR^+$ of real numbers is isomorphic to the multiplicative group $P$ of positive reals.
]

#proof[
  We exhibit the isomorphism $f: RR^+ -> P$ given by $f(x) = e^x$. It is a homomorphism since
  $
    e^(x+y) = e^x e^y
  $
  and it is an isomorphism because an inverse $log: P -> RR^+$ exists.
]

= Artin 2.3.11
#problem[
  Prove that the set $"Aut"(G)$ of automorphisms of a group $G$ forms a group, the law of composition being composition of functions.
]
#proof[
  There is an identity element, the identity automorphism that sends each element to itself.

  Function composition is associative: $f(g(h(x)))$ is the same whether we first form the function $f compose g$ and then evaluate it on $h(x)$, or first compute $g(h(x))$ and then feed that to $f$.

  Since each automorphism is a bijective map from $G$ to itself, it has an inverse map.

  Therefore all group axioms are satisfied and the set of automorphisms of a group $G$ form a group.
]

= Artin 2.3.12
#problem[
  Let $G$ be a group, and let $phi: G -> G$ be the map $phi(x) = x^(-1)$.

  (a) Prove that $phi$ is bijective.

  (b) Prove that $phi$ is an automorphism iff $G$ is abelian.
]

== (a)
$phi$ is its own inverse. Since an inverse exists, the map is bijective.

== (b)
#proof[

  ($=>$) Suppose $G$ is abelian. Since it is bijective, we need only check that $phi$ is a homomorphism:
  $
    phi(x y) = (x y)^(-1) = y^(-1) x^(-1) = x^(-1) y^(-1) = phi(x) phi(y) 
  $

  ($arrow.double.l$) Suppose that $phi$ is an automorphism, then it is a homomorphism, so for any $x, y in G$ we may evaluate
  $
       & phi(x^(-1) y^(-1)) = phi(x^(-1)) phi(y^(-1)) \
    => & (x^(-1) y^(-1))^(-1) = (x^(-1))^(-1) (y^(-1))^(-1) \
    => & (y^(-1))^(-1) (x^(-1))^(-1) = x y \
    => & y x = x y
  $
  so the group is abelian.
]

= Artin 2.4.3
#problem[
  Prove that the kernel and image of a homomorphism are subgroups.
]

#proof[
  (Kernel) Let $K$ be the kernel of a homomorphism $phi$ and let $a, b in K$. To prove it a subgroup we must show that inverses are in $K$ and that it's closed under the group law. For the former we see that
  $
       & phi(a a^(-1)) = phi(a) phi(a^(-1)) \
    => & phi(e) = e phi(a^(-1)) \
    => & e = phi(a^(-1))
  $
  showing that $a^(-1) in K$.

  To show that it's closed we do
  $
    phi(a b) = phi(a) phi(b) = e dot e = e
  $
  showing that $a b in K$. Therefore $K$ is a subgroup of $G$.

  (Image) Let $I$ be the image of a homomorphism $phi: G -> G'$ and let $c,d in I$. Then there exist $a, b in G$ such that
  $
    phi(a) = c "and" phi(b) = d .
  $

  Now,
  $
    c d = phi(a) phi (b) = phi(a b) in I ,
  $
  that is, $c d in I$ because $c d = phi("something")$.
  
  Also,
  $
    phi(a^(-1) a a^(-1)) = phi(a^(-1) a) phi(a^(-1)) = phi(e) phi(a)^(-1) = e dot c^(-1)
  $
  so $c^(-1) in I$ because $c^(-1) = phi("something")$. Therefore $I$ is a subgroup.
]
= Artin 2.4.6
#problem[
  Let $f: RR^plus -> CC^times$ be the map $f(x) = e^(i x)$. Prove that $f$ is a homomorphism, and determine its kernel and image.
]

#proof[
  If $a, b in RR^plus$ then
  $
    f(a+b) = e^(i(a+b)) = e^(i a) e^(i b) = f(a) f(b)
  $
  so $f$ is a homomorphism.

  Its kernel is $2 n pi$ where $n in ZZ$.

  Its image is the unit circle ${x + i y: x^2 + y^2 = 1}$.
]
= Artin 2.4.11
#problem[
  Let $G,H$ be cyclic groups, generated by elements $x,y$. Determine the condition on the orders $m,n$ of $x$ and $y$ so that the map sending $x^i arrow.squiggly.long y^i$ is a group homomorphism.
]

If $n$ is infinite then $m$ must be infinite.

If $n$ is finite then $m$ can either be infinite or a multiple of $n$.

= Bonus: Artin 2.2.4
= Bonus: Artin 2.2.11
= Bonus: Artin 2.2.12
= Bonus: Any two right cosets of $H$ in $G$ are either identical or have no elements in common
= Bonus: If $K = ker(phi)$ then $phi(a) = phi(b)$ iff the cosets $a K$ and $b K$ are equal
