#set page(numbering: "1")
#import "@preview/ctheorems:1.1.3": *
#import "@preview/physica:0.9.7": evaluated

#show: thmrules
#let lemma = thmbox("lemma", "Lemma", base: none)
#let theorem = thmbox("theorem", "Theorem", base: none)
#let definition = thmbox("definition", "Definition", base: none)
#let problem = thmbox("problem", "Problem", base: none)
#let proof = thmproof("proof", "Proof")
#let remark = thmbox("remark", "Remark")
#set math.mat(delim: "[")
#set math.equation(numbering: "(1)")

#show math.equation: it => {
  if it.block and not it.has("label") and it.numbering != none {
    counter(math.equation).update(v => v - 1)
    
    // Fix: Create a dictionary of fields, remove 'body', 
    // and pass 'it.body' positionally.
    let fields = it.fields()
    let _ = fields.remove("body") 
    
    math.equation(it.body, ..fields, numbering: none)
  } else {
    it
  }
}

#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  it
}

#outline(depth: 1)

Exercises are from Stephen Abbott's _Understanding Analysis_, Second Edition.

= Problem 1: Arzela-Ascoli Part I: A bounded sequence of functions on a countable domain has a convergent subsequence
Exercise 6.2.13

Let $A = {x_1, x_2, x_3, ...}$ be a countable set. For each $n in NN$ let $f_n$ be defined on $A$ and assume there exists an $M > 0$ such that $abs(f_(n)(x)) <= M$ for all $n in NN$ and $x in A$. 

== (a)

#lemma[
  Let $x_1 in A$ be fixed. Then $(f_(n)(x_1))$ contains a convergent subsequence.
]
#proof[
  Having fixed $x_1 in A$, the sequence $f_(n)(x_1)$ is a bounded sequence of real numbers. By the Bolzano-Weierstrass Theorem, it has a convergent subsequence.
]

Consider the subsequence of _functions_ generated by taking the functions whose _values_ at $x_1$ give the convergent subsequence above. To indicate that the subsequence of functions $f_(n_k)$ is generated by considering the values of the functions at $x_1$, we will use the notation $f_(n_k) = f_(1,k)$.

== (b)

By a similar argument, the sequence $(f_(1,k)(x_2))$ is a bounded sequence of real numbers, so it has a convergent subsequence.

Call this subsequence of functions $(f_(2,k))$. Since it is a subsequence of $(f_(1,k))$, this sequence of functions, when evaluated at $x_1$, also converges.

== (c)

In this manner, the sequence $f_(n,k)(x_(n+1))$ is a bounded sequence of real numbers, so it has a convergent subsequence. This defines the sequence $(f_(n+1,k))$.

$(f_(n,k))$ is a subsequence of $f_(m,k)$ whenever $m <= n$, so $f_(n,k)(x_m)$ converges whenever $m <= n$.

We will now define a single subsequence $(f_(m_k))$ of $(f_n)$:

Let $f_(m_1)$ be the first function in the sequence $(f_(1,k))$. Let $f_(m_2)$ be the second function in the sequence $(f_(2,k))$. In general, let $f_(m_j)$ be the $j$'th function in the sequence $(f_(j,k))$.

Then, for every $j$, all but a finite prefix (the first $j$ terms) of $(f_(m_k))$ is a subsequence of $f_(j,k)$. It is a valid subsequence since the indices $m_k$ are strictly increasing: $f_(m_(j+1))$ is the $j+1$'th term of $f_(j+1,k)$, which must appear later in $f_(j,k)$ than $f_(m_j)$ (the $j$'th term of $f_(j,k)$) since $f_(j+1,k)$ is a subsequence of $f_(j,k)$.

Hence $(f_(m_k)(x_i))$ converges for every point $x_i in A$.

= Problem 2: Arzela-Ascoli Part II: Defining equicontinuity
Exercise 6.2.14

A sequence of functions $(f_n)$ defined on a set $E subset.eq RR$ is called _equicontinuous_ if for every $epsilon > 0$ there exists a $delta > 0$ such that $abs(f_(n)(x) - f_(n)(y)) < epsilon$ for all $n in NN$ and $abs(x-y) < delta$ in $E$.

== (a)

Equicontinuity is a stronger condition than saying that each $f_n$ in the sequence is uniformly continuous, because a single $delta$ works for _every_ $f_n$.

== (b)

Let $g_(n)(x) = x^n$. Individually, each $g_n$ is uniformly continuous on $[0,1]$ since it's a continuous function on a compact domain. But $(g_n)$ is not equicontinuous. Qualitatively, this is because of what happens close to 1: the sequence gets closer and closer to the limiting function
$
  g(x) = cases(
    0 quad & "if" 0 <= x < 1,
    1 quad & "if" x = 1,
  )
$
so the jump from 0 to 1 happens in a shorter and shorter space as $n$ gets bigger. No single $delta$ can suffice for all $n$, because there will always be some $N$ after which the jump from very-close-to-0 to very-close-to-1 happens in a span of less than $delta$.

= Problem 3: Arzela-Ascoli Part III: A bounded, equicontinuous sequence of functions on a compact domain has a uniformly convergent subsequence
Exercise 6.2.15

For each $n in NN$, let $f_n$ be a function defined on $[0,1]$. Suppose that $f_n$ is bounded on $[0,1]$ -- that is, there exists an $M > 0$ such that $abs(f_(n)(x)) <= M$ for all $n in NN$ and $x in [0,1]$ -- and that the collection of functions $(f_n)$ is equicontinuous.

== (a)

Let $A = QQ inter [0,1]$. Since $QQ$ is countable, $A$ is also countable. By Problem 1, $evaluated(f_n)_A$ has a convergent subsequence. Equivalently, $(f_n)$ has a subsequence that converges pointwise on every point in $A$. Call it $(g_k)$.

== (b)

Let $epsilon > 0$. By equicontinuity, there exists a $delta > 0$ such that
$
  abs(g_(k)(x) - g_(k)(y)) < epsilon/3
$
for all $abs(x-y) < delta$ and $k in NN$. Let
$
  O = {V_(delta)(r): r in A}
$
be the set of $delta$-neighborhoods of every rational point in $[0,1]$. By the density of $QQ$ in $RR$, every real $x in [0,1]$ is within $delta$ of some rational point $q in A$. So $O$ is an open cover of $[0,1]$. By compactness, it has a finite subcover $phi$. Let $r_1, r_2, ..., r_m$ be the centers of $delta$-balls in $phi$.

The sequence of functions $(g_k)$ from part (a) converges pointwise on every $r in A$. In particular it converges for every $r_i$. That is, the sequences
$
  (g_(k)(r_i))
$
for $1 <= i <= m$ are convergent sequences of real numbers, hence they are Cauchy. So for each $1 <= i <= m$ there exists some $N_i in NN$ such that for all $s, t >= N_i$ we have
$
  abs(g_(s)(r_i) - g_(t)(r_i)) < epsilon/3 .
$

Let $N = max(N_1, N_2, ..., N_m)$, which is defined since $m$ is finite. Then
$
  abs(g_(s)(r_i) - g_(t)(r_i)) < epsilon/3
$
whenever $s,t >= N$.

== (c)

Let $x$ be an arbitrary point in $[0,1]$. By construction of the finite subcover $phi$ of $delta$-balls centered at the rational points $r_i$, there is at least one $r_i$ such that
$
  abs(x-r_i) < delta,
$
so
$
  abs(g_(k)(x) - g_(k)(r_i)) < epsilon/3
$
for all $k in NN$ by equicontinuity of $(f_n)$ (and therefore of its subsequence $(g_k)$) and the choice of $delta$.

Let $s, t >= N$. Then
$
  abs(g_(s)(x) - g_(t)(x)) \
  <= & abs(g_(s)(x) - g_(s)(r_i)) + abs(g_(s)(r_i) - g_(t)(r_i)) + abs(g_(t)(r_i) - g_(t)(x))\
  < & epsilon/3 + epsilon/3 + epsilon/3 \
  = & epsilon. 
$

Since $x$ was arbitrary and $N$ doesn't depend on $x$, by the Cauchy Criterion for Uniform Convergence, $(g_k)$ converges uniformly.

= Problem 4: A counterexample to show that uniform convergence is not enough for differentiation to commute with limits
Exercise 6.3.3

Define the sequence of functions
$
  f_(n)(x) = x/(1 + n x^2) .
$

Informally, each $f_n$ is bounded since $lim_(x->infinity) f_(n)(x) = 0$ and $lim_(x->-infinity) f_(n)(x) = 0$ and the denominator is never 0. So outside some compact domain the function goes to 0, and inside the compact domain containing 0 it doesn't blow up. Since it's bounded, its extrema must occur in some compact domain, so they must happen when its derivative is zero. In other words, there must exist some $M > 0$ and $x_0 > 0$ such that $abs(f_(n)(x)) < f_(n)(x_0)$ when $abs(x) > M$, so we may apply the Extreme Value Theorem to $[-M, M]$. Using the rules of differentiation, that happens when
$
  x = plus.minus 1 / sqrt(n) .
$

Here is a proof that $x_0 = 1 slash sqrt(n)$ is a global maximum for each $f_n$. $f_(n)(x_0) = 1/(2 sqrt(n))$. Applying the AM-GM inequality to 1 and $n x^2$, we have

$
  (1 + n x^2)/2 >= sqrt(n)x .
$

When $x > 0$, rearranging gives

$
  x/(1 + n x^2) <= 1/(2 sqrt(n))
$

as desired. This clearly holds for $x=0$ as well. Since $f_(n)(x) < 0$ when $x < 0$, this is a global maximum.

Since $f_n$ is an odd function, it has a global mininum at $-x_0$ with value $-1/(2 sqrt(n))$. 

Thus
$
  abs(f_(n)(x)) < 1/(2 sqrt(n))
$
for all $x in RR$. We use this to show uniform convergence of $(f_(n))$ to the constant function $f(x) = 0$.

Let $epsilon > 0$ be given. Then pick $N$ large enough such that
$
  abs(f_(N)(x) - f(x)) = abs(f_(N)(x)) < 1/(2 sqrt(N)) < epsilon .
$

This is possible since $1/(2 sqrt(n))$ converges to 0, and by the Archimedean Property. Since $1/(2 sqrt(n))$ is a strictly decreasing function of $n$, we have
$
  abs(f_(n)(x)) < epsilon wide "whenever" wide n >= N .
$

Since this choice of $N$ works for all $x in RR$, the convergence is uniform.

== (b)

Let $f = lim f_n$. Then $f(x) = 0$.

Using the rules of differentiation,
$
  f'_(n)(x) = (1 - n x^2)/((1 + n x^2)^2)
$
so
$
  lim f'_(n)(x) = cases(
    1 quad & "if" x = 0,
    0 quad & "if" x != 0
  )
$
since when $x = 0$ the function is identically 1, and when $x != 0$ we may divide the numerator and denominator by $n^2$ to see that the numerator goes to 0 while the denominator goes to $x^4 != 0$, so the limit is 0 by the Algebraic Limit Theorem.

(This already tells us that the sequence of derivatives doesn't converge uniformly: each derivative is continuous on all of $RR$ since it's a rational function with nonzero denominator, but the limit function has a discontinuity at zero.)

So, in this case, $f'(x) = lim f'_(n)(x)$ for every $x in RR backslash {0}$.

= Problem 5: If derivatives converge uniformly and the sequence converges at any point, it converges uniformly
Exercise 6.3.7

=== Proof idea

This is a simpler version of the technique used in the proof of the Differentiable Limit Theorem: apply MVT to $f_n - f_m$ and use the Cauchy Criterion for Uniform Convergence to bound the difference in the derivatives at a point.

My loose, intuitive idea of this theorem is that if the derivatives converge uniformly, then all the functions differ at most by a constant. So if we can pin down that constant, then the functions actually have to agree.

== Proof

#theorem[
  Let $(f_n)$ be a sequence of differentiable functions defined on the closed interval $[a,b]$, and assume $(f'_n)$ converges uniformly on $[a,b]$. If there exists a point $x_0 in [a,b]$ where $f_(n)(x_0)$ is convergent, then $(f_n)$ converges uniformly on $[a,b]$.
]
#proof[
  Let $epsilon > 0$ be given and let $x in [a,b]$ be arbitrary.
  
  Since the sequence of real numbers $(f_(n)(x_0))$ converges, it is Cauchy, so there exists some $N_1 in NN$ such that
  $
    abs(f_(n)(x_0) - f_(m)(x_0)) < epsilon/2
  $ <eq1>
  whenever $m,n >= N_1$.

  By uniform convergence of $(f'_n)$ and the Cauchy Criterion for Uniform Convergence, there exists some $N_2 in NN$ such that
  $
    abs(f'_(n)(y) - f'_(m)(y)) < epsilon/(2 (b-a))
  $
  whenever $m,n >= N_2$ for all $y in [a,b]$.

  Let $N = max(N_1, N_2)$ and let $m,n >= N$.

  If $x = x_0$ then
  $
    abs(f_(n)(x) - f_(m)(x)) = abs(f_(n)(x_0) - f_(m)(x_0)) < epsilon/2 < epsilon
  $
  by @eq1.

  Otherwise, by the Mean Value Theorem applied to the function $f_(m)(y) - f_(n)(y)$ on the interval $[x_0, x] subset.eq [a,b]$ (if $x < x_0$ the argument is the same), there exists some $alpha in [x_0,x]$ such that
  $
    frac((f_(n)(x) - f_(m)(x)) - (f_(n)(x_0) - f_(m)(x_0)), x - x_0) = f'_(n)(alpha) - f'_(m)(alpha),
  $
  but
  $
    abs(f'_(n)(alpha) - f'_(m)(alpha)) < epsilon/(2 (b-a)),
  $
  so
  $
    abs((f_(n)(x) - f_(m)(x)) - (f_(n)(x_0) - f_(m)(x_0))) < abs(x-x_0) epsilon/(2 (b-a)) .
  $

  Since $x,x_0 in [a,b]$,
  $
    abs(x - x_0) <= b-a,
  $
  so
  $
    abs((f_(n)(x) - f_(m)(x)) - (f_(n)(x_0) - f_(m)(x_0))) < abs(x-x_0) epsilon/(2(b-a)) <= epsilon/2 .
  $

  Now by the triangle inequality,
  $
    abs(f_(n)(x) - f_(m)(x)) \
     <= & abs((f_(n)(x) - f_(m)(x)) - (f_(n)(x_0) - f_(m)(x_0))) + abs(f_(n)(x_0) - f_(m)(x_0)) \
     < & epsilon/2 + epsilon/2 \
     = & epsilon .
  $

  So by the Cauchy Criterion for Uniform Convergence, since the choice of $N$ was independent of $x$, $(f_n)$ converges uniformly.
]
